### ISSUE TITLE
Port to Python 3 and update sugargame

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/pointillism-activity#25]

**Comment by mishra-tanay** [comment]
I would love to love to start my open source journey with this issue . Can I ?

**Comment by Aniket21mathur** [comment]
@mishra-tanay please go ahead :-).

Also, there is no need to ask for taking up an issue, just submit a pr and it will get reviewed by the contributors.

**Comment by mishra-tanay** [comment]
Can you please elaborate the issue ? Also a small tip on how to work on that

**Comment by quozl** [comment]
Ah, a newcomer.  Welcome.  You are not yet subscribed to our mailing list, please do so.  I'm sending you the latest _How to get started_ message.  General questions such as how to Port to Python 3 or how to update Sugargame are best posted to the mailing list, so that we keep issues comments relevant to the issue.  You can find some of the answers by reviewing other activities, other commits, and especially the [sugar-docs](https://github.com/sugarlabs/sugar-docs) repository.  I'll delete these comments as they are off-topic for the issue.  @Aniket21mathur, future issues might include [this reference](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md).

**Comment by Aniket21mathur** [comment]
> @Aniket21mathur, future issues might include [this reference](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md).

Thanks. Noted.

**Comment by ayushnawal** [comment]
@Aniket21mathur I think we can close the issue now :)
